name: Label Issue Based on Command

on:
  issues:
    types: [opened, closed]

jobs:
  run_command_and_label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Command
        run: |
          # Get the issue body
          issue_body=$(curl -s https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }} | jq -r '.body')

          # Analyze the issue body using jq
          output=$(echo "$issue_body" | jq '.[] | tostring | split("[x]") | length - 1')

          # Print the output for debugging
          echo "Output: $output"
      - name: Label Issue
        uses: actions/label-issue@v3
        with:
          issue_number: ${{ github.event.issue.number }}
          labels: ${{ github.event.issue.labels }}
          # Add or remove labels based on the output
          add_labels: |
            if [[ $output -eq 9 || $output -eq 10 ]]; then
              accepted,label2
            fi
